Fix_horaires_tarifs_style
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #100
Opened 2022-04-23 15:48 UTC by MGliem

2022-04-26 15:25 UTC, codelande submitted a review, later dismissed

2022-04-28 07:20 UTC, sblondeau requested changes

2022-04-28 07:20 UTC, sblondeau commented on src/View/Home/index.html.twig
> +										{% if rate.price == 'Contacter' %}
J'aime pas, car c'est dépendant de ce que tu as en db...
j'aimais pas non plus quand tu ajoutais une ligne dans ton tableau rates coté controller
je comprends que tu veuilles faire ça pour faciliter ta mise en page, cependant tu veux que ce soit le dernier élément de ta liste non ? 
donc rien ne t'empeche de rajojuter un tr araès ta boucle avec "Tarif groupe" / Contacter" sans avoir besoin de le mettre en db

2022-04-28 07:20 UTC, sblondeau commented on src/View/Home/index.html.twig
> +									<td class="py-3 fw-bold">Formules anniversaire</td>
en fait; tu le fais déjà bien comme ça ici pour les anniversaires ;-) !

2022-04-28 10:00 UTC, MATKYU submitted a review, later dismissed

2022-04-28 11:35 UTC, sblondeau requested changes

2022-04-28 11:35 UTC, sblondeau commented on src/View/Home/index.html.twig
> +									<td class="py-3 fw-bold">Tarifs de groupes / Comité d''entreprise (Carnet de tickets)</td>
celui là est à réintégrer dans la boucle non ? en elevant le lien

2022-04-28 11:56 UTC, MGliem commented on src/View/Home/index.html.twig
> +									<td class="py-3 fw-bold">Tarifs de groupes / Comité d''entreprise (Carnet de tickets)</td>
Non, il est en BD

2022-04-28 15:24 UTC, sblondeau approved these changes

2022-04-29 07:15 UTC, codelande approved these changes

2022-04-29 07:22 UTC, merged