S2 us33 contact
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #103
Opened 2022-04-27 09:29 UTC by MGliem

Contact form with sending mail

2022-04-27 16:18 UTC, codelande submitted a review, later dismissed
3000 lignes dans le composer lock, est ce normal ?

2022-04-27 20:44 UTC, MGliem commented
> 3000 lignes dans le composer lock, est ce normal ?

J'ai rajouté symfony mailer donc c'est sûrement lui qui a blindé le *.lock

2022-04-28 07:29 UTC, sblondeau requested changes

2022-04-28 07:29 UTC, sblondeau commented on src/Controller/ContactController.php
> +        if ($send !== '' && trim($send) === 'success') {
`if (trim($send) === 'success') {`
suffit non ?

2022-04-28 07:29 UTC, sblondeau commented on src/Controller/ContactController.php
> +         ->html($message)
non en fait ton mail, vu que c'est de l'html, tu peux le mettre dans un fichier twig
et tu auras `->html($this->twig->render('emailContact.html.twig, ['data'=>$data])`
sinon avec ta variable $message ou tu écrits du html, tu te retrouves avec de la vue dans ton controller et tu n'es plus en MVC (dans ce cas le mail est ta View )

2022-04-28 07:29 UTC, sblondeau commented on src/Controller/ContactController.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
doit etre dans ta méthode principale
ta méthode validate doit juste traiter la validation des données

et ça va te permettre de simplifier, c'est trop compliqué là avec tes $validations errors et inputs,

2022-04-28 10:04 UTC, codelande submitted a review, later dismissed

2022-04-28 11:38 UTC, sblondeau requested changes

2022-04-28 11:38 UTC, sblondeau commented on src/Controller/ContactController.php
> +            $inputs = array_map('trim', $_POST);
plutot $contact que $inputs
comme ça le nom de la variable reflète ce qu'il y a dedans

2022-04-28 16:40 UTC, sblondeau requested changes

2022-04-28 16:40 UTC, sblondeau commented on src/Controller/ContactController.php
> +        if ($send !== '' && trim($send) === 'success') {
non modifié

2022-04-28 16:40 UTC, sblondeau commented on src/Controller/ContactController.php
> +            $inputs = array_map('trim', $_POST);
non modifié

2022-04-28 16:40 UTC, sblondeau commented on src/View/Contact/index.html.twig
> +			<p class="text-danger">* champs obligatoires</p>
tu peux laisse comme ça, mais pour info, mettre des astérisques n'est pas la meilleure pratique en terme d'accessibilité/UX
mieux vaut ne rien mettre et éventuellement indiquer les champs optionnels

2022-04-29 06:57 UTC, MGliem commented on src/View/Contact/index.html.twig
> +			<p class="text-danger">* champs obligatoires</p>
J'ai du oublié de push encore ^^'. Pardon

2022-04-29 07:22 UTC, codelande submitted a review, later dismissed

2022-04-29 07:24 UTC, sblondeau submitted a review, later dismissed

2022-04-29 08:25 UTC, merged