S02 us08 cafet
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #108
Opened 2022-04-27 13:58 UTC by MATKYU

2022-04-27 16:21 UTC, codelande approved these changes

2022-04-28 11:40 UTC, sblondeau requested changes
image trop grosse, autour de 100ko c'est bien

2022-04-28 14:04 UTC, codelande approved these changes

2022-04-28 16:42 UTC, sblondeau requested changes
tu as créé une image moins grosse mais tu as laissé l'autre ;-)

2022-04-29 08:26 UTC, merged