S3 us29 admin attraction add
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #190
Opened 2022-05-02 07:33 UTC by MGliem

2022-05-02 07:36 UTC, codelande submitted a review, later dismissed

2022-05-02 10:20 UTC, Alexis-Thibault submitted a review, later dismissed

2022-05-02 10:23 UTC, sblondeau requested changes

2022-05-02 10:23 UTC, sblondeau commented on src/Controller/AdminAmusementController.php
> +                $errorsImage = ImageController::validateImage();
nope, tes validations ne doivent pas etre dans un ImageController
si vraiment tu voulais déporter, ça serait dans une classe dédiée ImageValidator ou qq chose comme ça, mais on ne va pas s'embêter pour le moment, rajouter une methode privée validateImage() dans ce controller là

2022-05-02 10:23 UTC, sblondeau commented on src/Controller/ImageController.php
> +        $maxFileSize = 1000000;
du coup tu crééra une constnate MAX_FILE_SIZE dans l'autre fichier

2022-05-02 10:23 UTC, sblondeau commented on config/config.php
> +define('APP_UPLOAD_LOCAL_PATH', __DIR__ . '/../public/uploads/');
hum, pas sur que cette constante soit vraiement nécessaire

2022-05-02 10:23 UTC, sblondeau commented on src/View/Admin/Amusement/_form.html.twig
> +    <label for="image" class="form-label mt-4">Image (1mo maximum | format jpeg, png, webp ou gif)</label>
si tu donnes des infos sur le type d'image ici (ce qui est très bien) il faut que ces infos soient fiables, et donc qu'ils proviennent direct de tes constantes, sinon risque d'avoir un message d'aide non en phase avec la vraie validation effectuée coté serveur

2022-05-02 13:26 UTC, Alexis-Thibault submitted a review, later dismissed

2022-05-02 14:22 UTC, sblondeau submitted a review, later dismissed

2022-05-03 10:13 UTC, Alexis-Thibault approved these changes

2022-05-03 10:51 UTC, merged