S3_US30_Attraction_Delete
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #199
Opened 2022-05-03 11:15 UTC by MGliem

2022-05-03 11:56 UTC, Alexis-Thibault submitted a review, later dismissed

2022-05-03 12:01 UTC, Alexis-Thibault approved these changes

2022-05-03 14:40 UTC, sblondeau requested changes

2022-05-03 14:40 UTC, sblondeau commented on src/Controller/AdminAmusementController.php
> +        if ($image !== '' && file_exists(APP_UPLOAD_PATH . $image)) {
le $image !== '' est-il vraiment utilie ? si c'est vide, le file_exists donne rien non ?

2022-05-03 14:40 UTC, sblondeau commented on src/View/Admin/_list.html.twig
>                          <button class="btn btn-danger w-fit d-flex gap-2 align-items-center">
ajoute le onclick + confirm aussi ;-)

2022-05-03 14:40 UTC, sblondeau commented on src/View/Admin/_list.html.twig
> +                            <input type="hidden" name="image" value="{{ item.image }}">
passe que l'id du coup ici

2022-05-03 14:40 UTC, sblondeau commented on src/Controller/AdminAmusementController.php
> +            $idAndImage = array_map('trim', $_POST);
pas la peine de passer le nom de l'image dans le POST
dans ton delete, tu commences par faire un selectOneById()
si tu récupères bien un tableau, alors tu fais le deleteImage et le delete() de la db
(je pense que tu peux au passage simplifier certaines des conditions en dessous)

2022-05-03 14:40 UTC, sblondeau commented on src/Controller/AdminAmusementController.php
> +        header('Location: /admin/attractions/');
et ajoute le petit message de success qui va bien :)

2022-05-03 15:16 UTC, Alexis-Thibault approved these changes

2022-05-04 07:53 UTC, Alexis-Thibault submitted a review, later dismissed

2022-05-04 08:39 UTC, sblondeau approved these changes

2022-05-04 08:39 UTC, sblondeau commented on 0
> +Could not open input file: echo
??

2022-05-04 08:49 UTC, Alexis-Thibault approved these changes

2022-05-04 09:38 UTC, merged