S03 us27 cafet add
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #211
Opened 2022-05-04 10:18 UTC by MATKYU

2022-05-04 12:12 UTC, Alexis-Thibault approved these changes

2022-05-04 12:14 UTC, codelande requested changes

2022-05-04 12:14 UTC, codelande commented on src/Controller/AdminCafeteriaController.php
> +        // $cafeteriaItems ??
commentaire ?

2022-05-04 12:14 UTC, codelande commented on src/View/Admin/Cafeteria/_form.html.twig
> +	<input type="hidden" value="{{ cafeteria.id }}" name="id">
d'ou viens cafeteria.id ?

2022-05-04 12:14 UTC, codelande commented on src/View/Admin/Cafeteria/_form.html.twig
> +	<label class="form-label" for="title">Category</label>
pareil, je ne pense pas que cafeteria est définie dans twig

2022-05-04 13:01 UTC, Alexis-Thibault approved these changes

2022-05-04 13:59 UTC, sblondeau requested changes

2022-05-04 13:59 UTC, sblondeau commented on src/View/Admin/Cafeteria/_form.html.twig
> +{# TODO : manage errors display #}
idem c'est fait en dessous donc enlève le commentaire (sinon on pense qu'il reste des choses à faire)

2022-05-04 15:23 UTC, Alexis-Thibault submitted a review, later dismissed

2022-05-04 21:13 UTC, sblondeau requested changes

2022-05-04 21:13 UTC, sblondeau commented on src/View/Admin/Cafeteria/_form.html.twig
> +{# TODO : manage errors display #}
commentaire TODO tjs là

2022-05-05 06:58 UTC, MGliem submitted a review, later dismissed

2022-05-05 07:16 UTC, sblondeau submitted a review, later dismissed

2022-05-05 08:59 UTC, Alexis-Thibault approved these changes

2022-05-05 09:06 UTC, merged