Add route for Edit , edit.html.twig, edit cafeteria manager and contr…
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #233
Opened 2022-05-05 12:34 UTC by MATKYU

…oler

2022-05-05 12:39 UTC, MGliem submitted a review, later dismissed

2022-05-05 14:00 UTC, sblondeau requested changes

2022-05-05 14:00 UTC, sblondeau commented on src/View/Admin/Cafeteria/_form.html.twig
> +		<option value="drink" {% if cafeteria.category == "drink" %} selected {% endif %}>Boissons</option>
utiliser constante

2022-05-05 14:00 UTC, sblondeau commented on src/Controller/AdminCafeteriaController.php
> +            $errors = $this->validate($cafeteria);
ajouter validation sur al category pour check si tu as bien drink ou snack et pas autre chose

2022-05-07 13:00 UTC, MGliem submitted a review, later dismissed

2022-05-08 21:14 UTC, sblondeau approved these changes

2022-05-09 08:35 UTC, MGliem approved these changes

2022-05-09 11:57 UTC, merged