S4 us21 admin tarif edit
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #260
Opened 2022-05-07 19:17 UTC by MGliem

2022-05-08 17:02 UTC, codelande approved these changes

2022-05-08 21:37 UTC, sblondeau requested changes

2022-05-08 21:37 UTC, sblondeau commented on src/Model/RateManager.php
> +        $query = 'INSERT INTO ' . self::TABLE . ' (description, price, rate_category_id)
ligne en trop le insert non  ?

2022-05-08 21:37 UTC, sblondeau commented on src/Model/RateManager.php
> +        $query .= 'rc.id AS category_id, rc.category FROM ' . self::TABLE . ' AS r';
tu es pas obligé de remettre un $query .= sur chaque ligne ^^ 
question de gout sans doute, mais je trouve pas que ce soit plus lisible

2022-05-08 21:37 UTC, sblondeau commented on src/Controller/AdminRateController.php
> +        } else {
je pense comprendre ce que tu veux faire, après manque peut-etre un message d'erreur ? 
j'aurais géré ça plutot dans les $errors, quite à mettre une condition coté twig si rate n'existe pas ?

2022-05-08 21:37 UTC, sblondeau commented on src/Controller/AdminRateController.php
> +        $rates = $rateManager->selectOneById((int)$id);
ça serait pas plutot $rate si tu as un select**One** ?

2022-05-09 08:10 UTC, codelande submitted a review, later dismissed

2022-05-09 11:56 UTC, sblondeau submitted a review, later dismissed

2022-05-09 14:39 UTC, merged