S4 us41 admin formule delete
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #264
Opened 2022-05-07 22:10 UTC by MGliem

2022-05-08 17:04 UTC, codelande approved these changes

2022-05-08 21:45 UTC, sblondeau requested changes

2022-05-08 21:45 UTC, sblondeau commented on src/Controller/AdminAnniversaryDetailController.php
> +            if ($id > 0) {
idem à l'autre PR? inutile cette condition (évite quand c'est possible d'imbriquer des trop de if ;-)

2022-05-09 08:23 UTC, codelande submitted a review, later dismissed

2022-05-09 11:59 UTC, sblondeau requested changes

2022-05-09 11:59 UTC, sblondeau commented on src/View/Admin/AnniversaryDetail/index.html.twig
>  										<form action="/admin/anniversaire/supprimer" method="post">
ajouter le confirm au onSubmit

2022-05-09 12:54 UTC, codelande approved these changes

2022-05-09 13:31 UTC, sblondeau approved these changes

2022-05-09 15:25 UTC, merged