add retour buton when possible
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #270
Opened 2022-05-08 12:22 UTC by codelande

2022-05-08 16:45 UTC, MGliem requested changes
Revoir le design et le placement du button (vu sur slack)

2022-05-09 08:48 UTC, MGliem approved these changes

2022-05-09 13:32 UTC, sblondeau approved these changes

2022-05-09 16:46 UTC, MGliem approved these changes

2022-05-09 21:33 UTC, merged