fix done
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #272
Opened 2022-05-08 16:58 UTC by Alexis-Thibault

2022-05-08 17:05 UTC, codelande approved these changes

2022-05-08 21:49 UTC, sblondeau requested changes

2022-05-08 21:49 UTC, sblondeau commented on src/Controller/AdminAnniversaryController.php
> +            if ($id > 0) {
voir retour sur PR de Max, cette condition n'apporte rien

2022-05-09 08:04 UTC, MGliem approved these changes

2022-05-09 13:33 UTC, merged