modif bouton deconnection admin
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #273
Opened 2022-05-08 17:03 UTC by Fabionic

2022-05-08 17:06 UTC, codelande submitted a review, later dismissed

2022-05-08 17:06 UTC, codelande commented on src/View/Components/_admin_navbar.html.twig
>  		</div>
profite en pour changer l'orthographe en "déconnexion"

2022-05-08 17:07 UTC, MGliem requested changes

2022-05-08 17:07 UTC, MGliem commented on src/View/Components/_admin_navbar.html.twig
> +			<a class="btn btn-success nav-item nav-link text-light fw-bolder fs-5 align-self-center" href="/logout">Déconnection</a>
On avait dit qu'on le mettait en blanc non ? (btn-Light) En vert ca fait bizarre pour un bouton de deconnexion

2022-05-08 17:21 UTC, Fabionic commented on src/View/Components/_admin_navbar.html.twig
> +			<a class="btn btn-success nav-item nav-link text-light fw-bolder fs-5 align-self-center" href="/logout">Déconnection</a>
C vrai c pas foufou !

2022-05-08 17:24 UTC, Fabionic commented on src/View/Components/_admin_navbar.html.twig
>  		</div>
Désolé j'avais modifié l'orthographe uniquement ds l'inspecteur et pensais l'avoir validé.

2022-05-08 21:18 UTC, MGliem approved these changes

2022-05-08 21:49 UTC, sblondeau approved these changes

2022-05-09 08:17 UTC, MGliem approved these changes

2022-05-09 08:28 UTC, merged