send mail when resa accepted
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #277
Opened 2022-05-09 17:12 UTC by codelande

2022-05-09 20:33 UTC, MGliem approved these changes

2022-05-09 21:37 UTC, sblondeau requested changes

2022-05-09 21:37 UTC, sblondeau commented on src/Controller/AdminAnniversaryController.php
> +            if ((int)$reservation['bool'] === 1) {
if($reservation['bool'])   est suffisant je pense

2022-05-09 21:37 UTC, sblondeau commented on src/View/Admin/Anniversary/mail.html.twig
> +		<p>Bonjour,
tu peux faire un tout tout petit peu plus de mise en page si c'est un mail "client"
un H1, le filtre |title sur le nom/prénom pour mettre la 1ere lettre en majuscule
et éventuellement un peu de style. Dans le cadre d'un email, tu es quasi obligé de passé par du style inline, donc là je peux accepter (par ex pour mettre une couleur de texte, reste sur du très basique et rapide)

2022-05-10 07:38 UTC, MGliem approved these changes

2022-05-10 07:46 UTC, sblondeau approved these changes

2022-05-10 07:46 UTC, merged