S4 us42 formule anniv edit
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #278
Opened 2022-05-09 18:31 UTC by MGliem

2022-05-09 19:52 UTC, codelande approved these changes

2022-05-09 21:40 UTC, sblondeau requested changes

2022-05-09 21:40 UTC, sblondeau commented on src/Controller/AdminAnniversaryDetailController.php
> +    public function index(string $msg = ''): string
$msg est une abbréviation => pas bien pour le nommage de variable :p appelle ça $message, ou $notification

2022-05-10 07:24 UTC, codelande approved these changes

2022-05-10 07:46 UTC, sblondeau approved these changes

2022-05-10 07:46 UTC, merged