S1 us6
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #31
Opened 2022-04-18 19:02 UTC by MGliem

EN TANT QUE visiteur
JE VEUX connaître la localisation du complexe sur la page d'accueil
AFIN DE my rendre facilement

2022-04-19 07:34 UTC, codelande approved these changes

2022-04-19 09:55 UTC, sblondeau requested changes

2022-04-19 18:43 UTC, MGliem commented on public/assets/css/style.css
> +@media screen and (max-width: 450px) {
Malheureusement le position n'est pas responsive de base. Par exemple position-md-fixed n'existe pas. C'est possible de le faire si on customise Bootstap avec Sass https://github.com/twbs/bootstrap/issues/28350 mais ce n'est pas encore dans nos cordes et cela demanderai d'installer bootstrap directement dans le projet

2022-04-20 15:47 UTC, sblondeau approved these changes

2022-04-20 15:47 UTC, sblondeau commented on public/assets/css/style.css
> +@media screen and (max-width: 450px) {
ok

2022-04-21 08:16 UTC, MATKYU approved these changes

2022-04-21 08:59 UTC, merged