fix title and event name
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #341
Opened 2022-05-10 19:38 UTC by codelande

2022-05-10 19:49 UTC, MGliem approved these changes

2022-05-11 06:55 UTC, sblondeau requested changes

2022-05-11 06:55 UTC, sblondeau commented on src/View/Events/_eventCards.html.twig
> +							<button type="button" class="btn btn-primary align-center" data-bs-toggle="modal" data-bs-target="#{{ event.title|replace({' ':''}) }}">
non ça ne va pas, car si 2 events ont le meme title, la modale va planter. Il faut que tu fasses `data-bs-target="#event{{ event.id}}` (on n'utilises pas un simple id en identifiant, c'est pour ça que j'ai mis le "event" devant

2022-05-11 06:55 UTC, sblondeau commented on src/View/Events/_eventCards.html.twig
> +				<div class="modal fade text-center" id="{{ event.title|replace({' ':''}) }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
et ici aussi

2022-05-11 07:39 UTC, sblondeau approved these changes

2022-05-11 07:39 UTC, merged