S01 us01
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #47
Opened 2022-04-20 12:30 UTC by codelande

2022-04-20 14:32 UTC, MATKYU commented on src/View/layout.html.twig
> +		<link
SPACE

2022-04-20 14:32 UTC, MATKYU commented on src/View/layout.html.twig
> +			{% block title %}Rigolou
Placement des blocks

2022-04-20 14:36 UTC, MATKYU requested changes

2022-04-20 14:36 UTC, MATKYU commented on src/View/layout.html.twig
> +		rel="icon" href="/assets/images/favicon.png">
Space

2022-04-20 14:36 UTC, MATKYU commented on src/View/layout.html.twig
> +			{% block title %}Rigolou
Block placement

2022-04-20 14:36 UTC, MATKYU commented on src/View/layout.html.twig
> +		rel="stylesheet" href="assets/css/style.css">
Space

2022-04-20 15:21 UTC, MATKYU approved these changes

2022-04-20 15:24 UTC, sblondeau submitted a review, later dismissed

2022-04-21 08:20 UTC, MGliem approved these changes

2022-04-21 09:06 UTC, merged