S1 us9
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #53
Opened 2022-04-21 10:19 UTC by Alexis-Thibault

2022-04-21 13:01 UTC, MATKYU submitted a review, later dismissed

2022-04-21 14:31 UTC, MATKYU approved these changes

2022-04-21 15:21 UTC, sblondeau commented on src/View/Amusements/index.html.twig
> +                <div class="col-lg-3 {% if loop.index % 2 == 0 %} order-lg-1 {% endif %}">
tu peux faire un if loop.index is odd  ou is even (d'ailleurs loop.index commence à 1 et loop.index0 commence à zéro

2022-04-22 09:12 UTC, MATKYU requested changes

2022-04-22 09:12 UTC, MATKYU commented on src/View/Amusements/index.html.twig
> +                {# {{ dump(constant('APP_UPLOAD_PATH') ~ amusement.image) }} #}
Var_dump ( au buchet )

2022-04-22 09:13 UTC, MATKYU approved these changes

2022-04-22 13:27 UTC, sblondeau requested changes

2022-04-22 13:27 UTC, sblondeau commented on database.sql
>  'Attraction phare qui permet aux enfant de jouer en toute sécurité',
aux enfant**s** (attention à l'orthographe, meme si ce sont des fausses données ;-))

2022-04-22 13:27 UTC, sblondeau commented on src/View/Amusements/index.html.twig
> +                    <img class="img-size rounded-4" src="{% if amusement.image is empty %}assets/images/1200x900_placeholder.png{% else %}{{constant('APP_UPLOAD_PATH') ~ amusement.image}}{% endif %}"
changer l'image du placeholder

2022-04-29 07:36 UTC, closed without merging