S01 10
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #54
Opened 2022-04-21 13:10 UTC by codelande

2022-04-21 13:26 UTC, Alexis-Thibault requested changes

2022-04-21 13:26 UTC, Alexis-Thibault commented on src/View/Cafeteria/index.html.twig
> +			</p>
PSR

2022-04-21 13:26 UTC, Alexis-Thibault commented on src/routes.php
> +
Supprimer le use ?

2022-04-21 13:34 UTC, Alexis-Thibault approved these changes

2022-04-21 15:24 UTC, sblondeau requested changes
réduire la taille de l'image, passer un jpg par ex, visez autour de 100ko max

2022-04-21 15:24 UTC, sblondeau commented on src/View/Cafeteria/index.html.twig
> +				<p class="col-md-6 offset-md-3">Un espace bar et salon de thé permet aux adultes comme aux enfants de boire une boisson froide ou chaude.Un snack permet de faire goûter les enfants. Les adultes p
Mettre un espace après le point  "chaude. Un snack"

2022-04-21 17:15 UTC, MGliem approved these changes

2022-04-21 20:44 UTC, sblondeau submitted a review, later dismissed

2022-04-22 07:30 UTC, MGliem approved these changes

2022-04-22 07:39 UTC, merged