Fix header overflow on amusement
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #56
Opened 2022-04-21 17:46 UTC by MGliem

Fixed header overflowing on amusement section and also cleaned up CSS specifi for home by moving it to home.css

2022-04-21 21:30 UTC, codelande approved these changes

2022-04-21 21:33 UTC, codelande requested changes

2022-04-21 21:33 UTC, codelande commented on src/View/Home/index.html.twig
> +	<main
reour a la ligne pour la class de main ?

2022-04-22 07:40 UTC, sblondeau approved these changes

2022-04-22 07:40 UTC, merged