Fix_Footer_Card_Navigate_Responsive
WildCodeSchool/2022-03-php-orleans-project-rigolou pull request #99
Opened 2022-04-23 13:12 UTC by MGliem

2022-04-26 15:23 UTC, codelande approved these changes

2022-04-26 15:35 UTC, sblondeau requested changes

2022-04-26 15:35 UTC, sblondeau commented on src/View/Home/index.html.twig
> +						<p>Eurl RIGOLOU<br>
juste pour en refuser une, mais tu as une balise `<address>` qui existe en html :p

2022-04-28 07:00 UTC, sblondeau approved these changes

2022-04-28 07:00 UTC, merged